bytecraftoy/aalto-project-2021

- src/client/Less/app.less
> Test commit, changed darker button hover color.

- src/client/src/App.tsx
- src/client/src/services/edgeService.ts
- src/client/src/types.ts
- src/server/domain/IEdge.ts
- src/server/migrations/1_create_initial_tables.sql
- src/server/route/index.ts
- src/server/route/path.ts
- src/server/route/routes/edge.ts
Edges are loaded from the database when the app starts, and saved there when created in the graph.
This is pretty much just a copy of the node stuff.
> Add edge saving

- src/client/src/App.tsx
- src/client/src/components/Graph.tsx
- src/client/src/index.css
- src/client/src/services/edgeService.ts
- src/client/src/services/nodeService.ts
- src/client/src/types.ts
- src/server/route/path.ts
- src/server/route/routes/edge.ts
- src/server/route/routes/node.ts
Merged node and edge deletion into a single branch. Resized graph to cover the whole page. Ids for newly created nodes are fetched from database instead of creating them in the client.
> Element deletion

- src/client/package.json
- src/client/src/App.tsx
Now should work the livereload when only css-file is changed.
> Css reload

- .eslintrc.js
- package-lock.json
- package.json
- src/client/package.json
- src/client/src/App.tsx
- src/client/src/index.tsx
- src/client/src/reportWebVitals.ts
- src/client/src/tests/App.test.tsx
- src/server/index.ts
- src/server/middlewares/checkMethod.ts
- src/server/middlewares/index.ts
- src/server/middlewares/logger.ts
- src/server/package-lock.json
- src/server/package.json
- src/server/route/index.ts
- src/server/route/path.ts
- src/server/route/router.ts
- src/server/route/routes/edge.ts
- src/server/route/routes/node.ts
adds a rule to eslint that blocks default exports
also changes default exports to named exports
also makes linter lint .tsx files
> Block default exports

- cypress/integration/sample_spec.js
- package.json
- src/client/src/App.tsx
- src/client/src/components/Graph.tsx
- src/client/src/components/NodeEdit.tsx
- src/client/src/services/nodeService.ts
- src/client/src/tests/components/Graph.test.tsx
- src/server/route/routes/node.ts
- src/server/tests/nodes.test.ts
> Ctrl click add node

- src/server/index.ts
- src/server/package-lock.json
- src/server/package.json
- src/server/route/routes/edge.ts
- src/server/route/routes/node.ts
- src/server/tests/edge.test.ts
Got rid of try catches in the backend. Additional checks for the backend so that the server responds correctly and not just a 500 or 404.
> Added try-catch middleware and corrected tests

- cypress/integration/sample_spec.js
- src/client/src/components/Graph.tsx
- src/client/src/components/Toolbar.tsx
- src/server/tests/edge.test.ts
The earlier branch was missing front (cypress) tests and the functionality disappeared along some merge. Added the cypress tests and the functionality again.
> No reversed edges fix

- package.json
Testing random stuff to fix the cypress tests in CI. The tests work locally.
> Cypress bug fix

- src/client/src/App.tsx
> set toast text to black

- cypress/integration/project_spec.js
- cypress/support/commands.js
Makes the cypress tests better by getting rid of one race condition that occasionally caused trouble
> Project cypress tests improvements

- .github/workflows/integrate.yml
- src/server/dbConfigs.ts
- src/server/index.ts
- src/server/tests/edge.test.ts
- src/server/tests/nodes.test.ts
- src/server/tests/project.test.ts
- src/server/tests/user.test.ts
Migration fail now shuts down server instead of dropping all tables.
> Proper migrations

- cypress/integration/project_spec.js
- src/client/src/components/Graph.tsx
- src/client/src/services/edgeService.ts
- src/server/route/routes/edge.ts
- src/server/tests/edge.test.ts
Also changed the .graph classname from cypress to "flow-wrapper"
> source and target of an edge cannot be the same

- src/docs/docusaurus.config.js
- src/docs/openapi.json
- src/docs/package-lock.json
- src/docs/package.json
- src/docs/yarn.lock
- src/server/package-lock.json
- src/server/package.json
- src/server/route/routes/edge.ts
API documentation can now be done by just putting comments in correct form. API documentation can be found in docusaurus at localhost:3000/api. NavLink coming soon. To save changes in the API documentation, run "npm run openapi" on the server.
> openapi and comment parser added

- src/docs/src/pages/help.md
Rewrite the "How to use app?" tutorial on the /help page of documentation. Graphs are now called "projects", nodes are "tasks" and edges are "connections".
> Update help page

- src/client/src/components/Graph.tsx
single line removal
edit: now more lines
> remove tag input from proj view

- src/client/jest-config/setupTests.ts
- src/client/src/components/Graph.tsx
- src/client/src/services/socket.ts
- src/client/src/services/userService.ts
- src/server/helper/socket.ts
- src/server/index.ts
- src/server/route/routes/edge.ts
- src/server/route/routes/node.ts
- src/server/tests/project.test.ts
edge addition, deletion and reversing
node addition, deletion and movement
also should make sockets work in heroku (and anywhere that's not localhost, in general)
> add real-time collaboration to graph

- README.md
- src/client/src/App.tsx
- src/server/migrations/7_create_description_node.sql
- src/server/package-lock.json
- src/server/route/routes/node.ts
- src/server/tests/nodes.test.ts
- src/server/tests/project.test.ts
- src/server/tests/testHelper.ts
- types.ts
> Fix readme

- README.md
- cypress/integration/sample_spec.js
- src/client/src/App.tsx
- src/client/src/components/NodeDetail.tsx
- src/client/src/components/NodeForm.tsx
- src/server/migrations/7_create_description_node.sql
- src/server/package-lock.json
- src/server/route/routes/node.ts
- src/server/tests/nodes.test.ts
- src/server/tests/project.test.ts
- src/server/tests/testHelper.ts
- types.ts
Now on the sidebar description is shown, can be edited, and doesn't show if it's empty.
> Node description frontend

- cypress/support/commands.js
- src/client/src/components/RegistrationForm.tsx
- src/client/src/tests/components/RegistrationForm.test.tsx
- src/server/route/routes/user.ts
- src/server/tests/project.test.ts
- src/server/tests/testHelper.ts
- src/server/tests/user.test.ts
- testmock.ts
The pop up moves the registration form. All the error messages could be changed to toast notifications instead in a later pull.
> password now needs to be at least 12 characters longs

- src/client/src/App.css
- src/client/src/components/Graph.tsx
- src/client/src/pages/GraphPage.tsx
also move project and permission check to GraphPage
> add loading spinner to project loading

- src/client/src/components/Graph.tsx
> Cmd+click fix

- src/client/jest.config.js
- src/client/src/tests/components/Project.test.tsx
The .tsx tests got accidentally disabled when adding code coverage, whoops.
> Re-enable frontend tests

- src/server/helper/logging.ts
- src/server/route/routes/assignment.ts
- src/server/route/routes/edge.ts
- src/server/route/routes/node.ts
- src/server/route/routes/project.ts
- src/server/route/routes/tag.ts
- src/server/route/routes/user.ts
So this skips all GET requests, but every POST/PUT/DELETE should be covered.
> Add logging to all endpoints which modify the database

- cypress/support/commands.js
- src/client/src/components/TopBar.tsx
- src/client/src/index.css
Changed Home button to Depsee-logo. In my opinion this looks good but maybe a bit less intuitive - another option would be to keep the Home button as it is, and append Depsee-logo to the right of Home and Help buttons.
> Show app name in top left corner

- src/server/route/path.ts
- src/server/route/routes/tag.ts
- types.ts
Change the server-side routes to later enable tagging nodes
> Tag to node routes

- src/client/src/components/NodeTagEdit.tsx
Client component for adding tags to nodes in node details view
> Tag-to-node client component
